name: CI Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.set_version.outputs.version }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: set version
              id: set_version
              run: |
                  version=$(date +'%Y%m%d.%H%M%S')
                  echo "version=$version" >> "$GITHUB_OUTPUT"
                  printf '{"version": "%s" }' "$version" > public/version.json

            - name: Build
              run: |
                  npm ci && npm run build
                  cp dist/index.html dist/404.html

            - name: Run tests
              run: |
                  npx playwright install --with-deps chromium
                  npm run test:coverage

            - name: Update coverage
              run: |
                  coverage_pct=$(grep -o '"pct":[0-9.]*' coverage/coverage-summary.json | head -n 1 | cut -d ':' -f 2)
                  color=$(echo "$coverage_pct < 80" | bc -l | awk '{if ($1) print "yellow"; else print "green"}')
                  curl https://img.shields.io/badge/Coverage-$coverage_pct%25-$color -o coverageBadge.svg
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "generated coverage badge: $coverage_pct%"
                  git push

            - name: Update pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist/

    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
